name: chat_gpt_app
description: Chat GPT App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chat_bubbles: ^1.4.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  rx_notifier: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
