name: chat_gpt_app
description: Chat GPT App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chat_bubbles: ^1.4.1
  chat_gpt_flutter: ^1.0.11
  cupertino_icons: ^1.0.5
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  rx_notifier: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
